version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg_test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SETUP_EMAIL: admin@admin.com
      PGADMIN_SETUP_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass_file:/pgpass/pgpass_file
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pg_net

volumes:
  pg_data:
  pgadmin_data:

networks:
  pg_net:
    driver: bridge